---
- hosts: all
  gather_facts: false
  ignore_unreachable: yes
  tasks:
    - name: Create auth rule
      cisco.ise.network_access_authorization_rules:
        ise_hostname: "{{ ansible_host }}"
        ise_verify: "{{ ise_verify }}"
        policyId: "{{ policyid }}"
        #id: "{{ id }}"
        state: present
        profile:
          - "{{ item.1 }}"
        rule:
          #id: "{{ id }}"
          name: "{{ item.0 }}"
          condition:
            attributeName: "uid"
            attributeValue: "{{ item.0 }}"
            conditionType: "ConditionAttributes"
            dictionaryName: "OpenLDAP"
            operator: "equals"
      loop: "{{ auth_profile_input }}"
      register: results2
    - name: Display 
      debug:
        var: results2