---
- hosts: all
  gather_facts: false
  ignore_unreachable: yes
  tasks:
    - name: Update auth rule
      cisco.ise.network_access_authorization_rules:
        ise_hostname: "{{ ansible_host }}"
        ise_verify: "{{ ise_verify }}"
        policyId: "{{ policyid }}"
        id: "{{ id }}"
        state: present
        profile: "{{ item.1 }}"
        rule:
          id: "{{ id }}"
          name: "{{ item.0 }}"
          condition:
            attributeName: "{{ item.2 }}"
            attributeValue: "ConditionAttributes"
            conditionType: "{{ item.3 }}"
            dictionaryName: "{{ item.4 }}"
            operator: "{{ item.5 }}"
      with_items:
        - auth_profile_input
      register: results2
    - name: Display 
      debug:
        var: results2