---
- hosts: all
  gather_facts: false
  ignore_unreachable: yes
  tasks:
    - name: Create auth rule
      cisco.ise.network_access_authorization_rules:
        ise_hostname: "{{ ansible_host }}"
        ise_verify: "{{ ise_verify }}"
        policyId: "{{ policyid }}"
        #id: "{{ rule_id }}"
        state: present
        profile: "{{ item.profiles }}"
        rule:
          #id: "{{ rule_id }}"
          name: "{{ item.rule_name }}"
          condition:
            attributeName: "uid"
            attributeValue: "{{ item.rule_name }}"
            conditionType: "ConditionAttributes"
            dictionaryName: "OpenLDAP"
            operator: "equals"
      loop: "{{ auth_profile_input }}"
      #register: results2
      tags: update
    # - name: Display 
    #   debug:
    #     var: results2
    - name: Get all rules
      cisco.ise.network_access_authorization_rules_info:
        ise_hostname: "{{ ansible_host }}"
        ise_verify: "{{ ise_verify }}"
        policyId: "{{ policyid }}"
      register: all_rules
      tags: get_all_rules
    - name: Get rule IDs in a list
      ansible.builtin.set_fact:
        rule_id_list: "{{ rule_id_list | default([]) }} + ['{{ item.rule.id }}']"
      with_items: "{{ all_rules.ise_response}}"
      # when: 
      #   - all_rules.ise_response.rule.default == False
      #   - all_rules.ise_response.rule.id is defined
      tags: get_all_rules
    - name: Display 
      debug:
        var: rule_id_list  
      tags: get_all_rules
    - name: Delete auth rules by ID
      cisco.ise.network_access_authorization_rules:
        ise_hostname: "{{ ansible_host }}"
        ise_verify: "{{ ise_verify }}"
        policyId: "{{ policyid }}"
        id: "{{ rule_id }}"
        state: absent
      tags: delete